using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using AttackPattern = System.Collections.Generic.List<Bullets.AttackStep>;

namespace Bullets
{
    public static class AttackPatterns
    {
        public static AttackStep GetNextAttackStep(AttackPatternType pattern, int stepNumber)
        {
            if (!_attackPatterns.ContainsKey(pattern))
            {
                // ReSharper disable once StringLiteralTypo
                throw new ArgumentException($"Welp, you dun goofed. Ain't no such {pattern} pattern.");
            }

            AttackPattern attackPattern = _attackPatterns[pattern];
            return attackPattern[stepNumber % attackPattern.Count];
        }

        private static readonly IDictionary<AttackPatternType, AttackPattern> _attackPatterns = new Dictionary<AttackPatternType, AttackPattern>
        {
                #region AttackPattern Cross

                {
                        AttackPatternType.Cross, new List<AttackStep>
                        {
                                new AttackStep(new List<ProjectileAttack> {
                                        new ProjectileAttack(new Vector2(1f, 0f), ProjectileType.Normal),
                                        new ProjectileAttack(new Vector2(-1f, 0f), ProjectileType.Normal),
                                }, .7f),
                                new AttackStep(new List<ProjectileAttack>
                                {
                                        new ProjectileAttack(new Vector2(0f, 1f), ProjectileType.Normal),
                                        new ProjectileAttack(new Vector2(0f, -1f), ProjectileType.Normal),
                                }, .7f),
                                new AttackStep(new List<ProjectileAttack>
                                {
                                        new ProjectileAttack(new Vector2(1f, 0f), ProjectileType.Normal),
                                        new ProjectileAttack(new Vector2(-1f, 0f), ProjectileType.Normal),
                                }, .7f),
                                new AttackStep(new List<ProjectileAttack>
                                {
                                        new ProjectileAttack(new Vector2(0f, 1f), ProjectileType.Normal),
                                        new ProjectileAttack(new Vector2(0f, -1f), ProjectileType.Normal),
                                }, 4f),
                        }
                },

                #endregion

                #region AttackPattern WazerWall

                {
                        AttackPatternType.WazerWall, new List<AttackStep>
                        {
                                new AttackStep(new List<ProjectileAttack> { new ProjectileAttack(Vector2.zero, ProjectileType.WazerBeam) }, 0.05f),
                                new AttackStep(new List<ProjectileAttack> { new ProjectileAttack(Vector2.zero, ProjectileType.WazerBeam, false) }, 0.05f),
                                new AttackStep(new List<ProjectileAttack> { new ProjectileAttack(Vector2.zero, ProjectileType.WazerBeam, false) }, 0.05f),
                                new AttackStep(new List<ProjectileAttack> { new ProjectileAttack(Vector2.zero, ProjectileType.WazerBeam, false) }, 0.05f),
                                new AttackStep(new List<ProjectileAttack> { new ProjectileAttack(Vector2.zero, ProjectileType.WazerBeam, false) }, 0.05f),
                                new AttackStep(new List<ProjectileAttack> { new ProjectileAttack(Vector2.zero, ProjectileType.WazerBeam, false) }, 0.05f),
                                new AttackStep(new List<ProjectileAttack> { new ProjectileAttack(Vector2.zero, ProjectileType.WazerBeam, false) }, 0.05f),
                                new AttackStep(new List<ProjectileAttack> { new ProjectileAttack(Vector2.zero, ProjectileType.WazerBeam, false) }, 0.05f),
                                new AttackStep(new List<ProjectileAttack> { new ProjectileAttack(Vector2.zero, ProjectileType.WazerBeam, false) }, 0.05f),
                                new AttackStep(new List<ProjectileAttack> { new ProjectileAttack(Vector2.zero, ProjectileType.WazerBeam, false) }, 0.05f),
                                new AttackStep(new List<ProjectileAttack> { new ProjectileAttack(Vector2.zero, ProjectileType.WazerBeam, false) }, 0.05f),
                                new AttackStep(new List<ProjectileAttack> { new ProjectileAttack(Vector2.zero, ProjectileType.WazerBeam, false) }, 0.05f),
                                new AttackStep(new List<ProjectileAttack> { new ProjectileAttack(Vector2.zero, ProjectileType.WazerBeam, false) }, 0.05f),
                                new AttackStep(new List<ProjectileAttack> { new ProjectileAttack(Vector2.zero, ProjectileType.WazerBeam, false) }, 0.05f),
                                new AttackStep(new List<ProjectileAttack> { new ProjectileAttack(Vector2.zero, ProjectileType.WazerBeam, false) }, 7.2f),
                        }
                },

                #endregion

                #region AttackPattern FireSpiral

                {
                        AttackPatternType.FireSpiral, new List<AttackStep>
                        {
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(0), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(1), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(2), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(3), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(4), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(5), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(6), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(7), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(8), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(9), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(10), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(11), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(12), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(13), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(14), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(15), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(16), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(17), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(18), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(19), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(20), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(21), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(22), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(23), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(24), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(25), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(26), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(27), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(28), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(29), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(30), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(31), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(32), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(33), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(34), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(35), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(36), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(37), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(38), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(39), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(40), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(41), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(42), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(43), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(44), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(45), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(46), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(47), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(48), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(49), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(50), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(51), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(52), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(53), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(54), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(55), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(56), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(57), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(58), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(59), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(60), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(61), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(62), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(63), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(64), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(65), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(66), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(67), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(68), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(69), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(70), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(71), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(72), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(73), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(74), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(75), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(76), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(77), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(78), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(79), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(80), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(81), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(82), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(83), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(84), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(85), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(86), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(87), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(88), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(89), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(90), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(91), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(92), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(93), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(94), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(95), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(96), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(97), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(98), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(99), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(100), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(101), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(102), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(103), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(104), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(105), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(106), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(107), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(108), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(109), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(110), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(111), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(112), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(113), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(114), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(115), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(116), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(117), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(118), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(119), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(120), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(121), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(122), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(123), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(124), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(125), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(126), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(127), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(128), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(129), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(130), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(131), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(132), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(133), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(134), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(135), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(136), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(137), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(138), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(139), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(140), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(141), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(142), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(143), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(144), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(145), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(146), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(147), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(148), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(149), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(150), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(151), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(152), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(153), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(154), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(155), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(156), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(157), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(158), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(159), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(160), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(161), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(162), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(163), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(164), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(165), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(166), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(167), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(168), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(169), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(170), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(171), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(172), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(173), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(174), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(175), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(176), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(177), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(178), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(179), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(180), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(181), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(182), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(183), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(184), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(185), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(186), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(187), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(188), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(189), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(190), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(191), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(192), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(193), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(194), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(195), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(196), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(197), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(198), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(199), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(200), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(201), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(202), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(203), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(204), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(205), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(206), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(207), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(208), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(209), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(210), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(211), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(212), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(213), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(214), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(215), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(216), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(217), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(218), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(219), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(220), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(221), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(222), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(223), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(224), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(225), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(226), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(227), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(228), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(229), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(230), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(231), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(232), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(233), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(234), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(235), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(236), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(237), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(238), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(239), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(240), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(241), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(242), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(243), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(244), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(245), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(246), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(247), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(248), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(249), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(250), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(251), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(252), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(253), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(254), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(255), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(256), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(257), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(258), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(259), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(260), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(261), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(262), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(263), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(264), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(265), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(266), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(267), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(268), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(269), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(270), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(271), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(272), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(273), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(274), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(275), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(276), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(277), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(278), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(279), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(280), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(281), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(282), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(283), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(284), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(285), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(286), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(287), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(288), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(289), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(290), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(291), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(292), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(293), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(294), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(295), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(296), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(297), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(298), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(299), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(300), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(301), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(302), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(303), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(304), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(305), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(306), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(307), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(308), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(309), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(310), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(311), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(312), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(313), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(314), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(315), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(316), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(317), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(318), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(319), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(320), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(321), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(322), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(323), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(324), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(325), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(326), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(327), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(328), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(329), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(330), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(331), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(332), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(333), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(334), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(335), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(336), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(337), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(338), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(339), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(340), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(341), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(342), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(343), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(344), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(345), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(346), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(347), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(348), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(349), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(350), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(351), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(352), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(353), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(354), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(355), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(356), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(357), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(358), ProjectileType.FireBall)}, 0.1f),
                                new AttackStep(new List<ProjectileAttack> {new ProjectileAttack(FromDegree(359), ProjectileType.FireBall)}, 27f),
                        }
                },

                #endregion
        };

        private static Vector2 FromRadian(float radian)
        {
            return new Vector2(Mathf.Cos(radian), Mathf.Sin(radian));
        }

        private static Vector2 FromDegree(float degree)
        {
            return FromRadian(degree * Mathf.Deg2Rad);
        }
    }

    public readonly struct AttackStep
    {
        public IList<ProjectileAttack> ProjectileAttacks { get; }
        public float StepDelay { get; }

        public AttackStep(IList<ProjectileAttack> attackSteps, float stepDelay)
        {
            ProjectileAttacks = attackSteps.ToList();
            StepDelay = stepDelay;
        }
    }

    public readonly struct ProjectileAttack
    {
        public Vector2 Trajectory { get; }
        public ProjectileType Type { get; }
        public bool PlayAudio { get; }

        public ProjectileAttack(Vector2 trajectory, ProjectileType type, bool playAudio = true)
        {
            Trajectory = trajectory;
            Type = type;
            PlayAudio = playAudio;
        }
    }
}
